### ISSUE TITLE
"error": "Unauthorized" Ao rodar projeto "floating-phone"

### ISSUE THREAD

**Issue by LeandroVCastro** [teravoz/webphone-examples#1]
Depois de fazer todas as configurações, como orientado do read.me, montar e rodar a imagem no docker, um erro é apresentado no console.

> Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Ao abrir o erro na aba network e inspecionar a requisição, percebe-se que o acesso não foi autorizado.

`
{
  "error": "Unauthorized"
}`

Este repositório ainda é ativo e é dado manutenção no mesmo?
Em caso de sim, tenho interesse em acompanhar e dar uma estudada na forma de implementação do protocolo WebRTC.

**Comment by rikez** [comment]
Olá Leandro, este erro ocorre porque você tem que gerar a API_KEY no sistema da Teravoz. Você já é nosso cliente ?

**Comment by rikez** [comment]
O objetivo desse repositório é fornecer exemplo de implementacao de webphone utilizando a nossa biblioteca de webrtc. Para isso é necessário ser um cliente Teravoz.

**Comment by LeandroVCastro** [comment]
Consegui fazer o projeto funcionar.
Ao pedir pra configurar o usuário e senha no código, eu entendi que era o usuário e senha da API e não dos ramais.
Uma sugestão seria deixar isso claro na documentação, pois foi uma dúvida que eu tive.

Abraços.
